//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationColumns {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class conficN : global::System.Configuration.ApplicationSettingsBase {
        
        private static conficN defaultInstance = ((conficN)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new conficN())));
        
        public static conficN Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\35498\\source\\repos\\NonStandartRequests\\NonStandartRequests\\bin\\Debug\\Non" +
            "StandartRequests.exe.config")]
        public string nonstandartrequestConfigPath {
            get {
                return ((string)(this["nonstandartrequestConfigPath"]));
            }
            set {
                this["nonstandartrequestConfigPath"] = value;
            }
        }
    }
}
